# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robotics Club CIT Kokrajhar
email: roboticsclub@cit.ac.in
description: An excellent platform for students to unleash their creativity and get all kinds resources to work on innovative ideas about robotics and technology
baseurl: ""
url: "https://roboticsclub.cit.ac.in"
logo: "/assets/img/icon/main-logo.png"
social:
  name: Robotics Club CIT Kokrajhar
  links:
    - https://www.facebook.com/themoderngeeks
    - https://github.com/robotics-club-citk
    - https://youtube.com/channel/UCo7ZitSCcgWNEsQVVzBx41g

webmaster_verifications:
  google: on-j_4e55BohxmVyp9ynfpEmDeFeNfO9QEv5n4O_lSQ

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "members"
    values:
      robots: noindex
      sitemap: false
      layout: "member"
      description: "Member of Robotics club CIT Kokrajhar"
  - scope:
      path: ""
      type: "projects"
    values:
      sitemap: false
      layout: "project"
  - scope:
      path: ""
      type: "events"
    values:
      sitemap: false
      layout: "event"

collections:
  members:
    output: true
    permalink: /members/:path/
  projects:
    output: true
    permalink: /projects/:path/
  events:
    output: true
    permalink: /events/:path/

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
