# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robotics Club CIT Kokrajhar
email: roboticsclub@cit.ac.in
description: Explore the world of robotics with Robotics Club CIT Kokrajhar. It is an excellent platform for students to unleash their creativity and get all kinds resources to work on innovative ideas about robotics and technology
baseurl: ""
url: ""

github_username: robotics-club-citk

# Build settings
markdown: kramdown
permalink: pretty


collections:
  -
    members:
      output: true
  -
    projects:
      output: true


sass:
  sass_dir: _sass
  style: compressed


exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
